### ISSUE TITLE
Multiple Stage Docker Build fails to publish

### ISSUE THREAD

**Issue by CosyOranges** [esatterwhite/semantic-release-docker#21]
When using the plugin to create two images (the second depending on the first) the build succeeds, however the publish stage fails because it cannot remove the image because it has children.

Details:
1) Creating two images
```
["@codedependant/semantic-release-docker",
          {
            "dockerTags": [
              "latest",
              "{major}-latest",
              "{major}-{minor}-latest",
              "{version}"
            ],
            "dockerRegistry": "registry",
            "dockerProject": "project",
            "dockerImage": "base-image",
            "dockerContext": "base",
            "dockerFile": "base/Dockerfile",
            "dockerLogin": false,
            "dockerArgs": {
              "SOME_ARG": "x.x.x"
            }
          }
        ],
        [
          "@codedependant/semantic-release-docker",
          {
            "dockerTags": [
              "latest",
              "{major}-latest",
              "{major}-{minor}-latest",
              "{version}"
            ],
            "dockerRegistry": "registry",
            "dockerProject": "project",
            "dockerImage": "image-depending-on-base-image",
            "dockerContext": "python-base",
            "dockerFile": "python-base/Dockerfile",
            "dockerLogin": false,
            "dockerArgs": {
              "BASE_IMAGE": "registry/project/base-image:{build}"
            }
          }
        ],
```

2) Results:
Build Finishes fine but the publish step creates this error message:
```
[11:11:11 PM] [semantic-release] › ✖  Failed step "publish" of plugin "@codedependant/semantic-release-docker"
[11:11:11 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 123: xargs docker rmi -f
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
Error response from daemon: conflict: unable to delete xxxxxxxxxxxxxx (cannot be forced) - image has dependent child images
    at makeError (/usr/local/lib/node_modules/@codedependant/semantic-release-docker/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/@codedependant/semantic-release-docker/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async publish (/usr/local/lib/node_modules/@codedependant/semantic-release-docker/lib/publish.js:32:3)
    at async validator (/usr/local/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/usr/local/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 123: xargs docker rmi -f',
  command: 'xargs docker rmi -f',
  exitCode: 123,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
```

**Comment by esatterwhite** [comment]
I'm not entirely sure I would expect this to work. Its not really the way semantic release is intended to be used.

I think it the simple case there could be a flag to not delete the image during the clean up step.

**Comment by esatterwhite** [comment]
In this case, do you actually need to publish the base image as well?

**Comment by CosyOranges** [comment]
Yes ideally both images would be able to be published, currently a workaround is to just rebuild the first image in the second, but in an ideal world (😅 ) this wouldn't be the case. I was curious if it had to do with the way you run the clean command? Is it possible that moving from the image id to the image tag when cleaning could fix this?
(This is just something I've had to do locally when trying to remove images with children)

**Comment by esatterwhite** [comment]
Yes, the clean command is trying to remove all the layers related to  the build. If the build were being used to generate base images that would be a problem. 

It could easily be a setting to make it not do that.

**Comment by esatterwhite** [comment]
[v4.3.0] has an option to disable the autoclean
