### ISSUE TITLE
Error when using multiple times

### ISSUE THREAD

**Issue by buehler** [esatterwhite/semantic-release-docker#28]
Hey there

I really do love this plugin for semantic release. However, when using with multiple locations, the pushing part results in a "no such image" error.

https://github.com/smartive-education/cas-fee-adv-qwacker-api/blob/7610ddae918477787e180ef01b4dabbb024d4b68/.releaserc.json#L7-L49

The configuration above is used to create a set of images for ghcr.io and one for the google artifact repository.

When running the action, the following logs appear:
![image](https://user-images.githubusercontent.com/1067213/193217974-1982cf28-7298-41b8-9ecd-ee4b3ae8773b.png)

```
[7:31:42 AM] [semantic-release] › ℹ  Start step "prepare" of plugin "@codedependant/semantic-release-docker"
[7:31:42 AM] [semantic-release] [@codedependant/semantic-release-docker] › ℹ  building image europe-west6-docker.pkg.dev/ost-cas-adv-fee/qwacker-api-docker/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e
[7:31:42 AM] [semantic-release] [@codedependant/semantic-release-docker] › ⬤  build command: docker build --quiet --tag europe-west6-docker.pkg.dev/ost-cas-adv-fee/qwacker-api-docker/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e --build-arg SRC_DIRECTORY=cas-fee-adv-qwacker-api --build-arg TARGET_PATH=. --build-arg NPM_PACKAGE_NAME=qwacker-api --build-arg NPM_PACKAGE_SCOPE --build-arg CONFIG_NAME=cas-fee-adv-qwacker-api --build-arg CONFIG_PROJECT=ost-cas-adv-fee/qwacker-api-docker --build-arg GIT_SHA=7610ddae918477787e180ef01b4dabbb024d4b68 --build-arg GIT_TAG=v1.1.2 --build-arg BUILD_VERSION=1.1.2 --build-arg COMMIT_SHA=7610ddae918477787e180ef01b4dabbb024d4b68 -f /home/runner/work/cas-fee-adv-qwacker-api/cas-fee-adv-qwacker-api/Dockerfile /home/runner/work/cas-fee-adv-qwacker-api/cas-fee-adv-qwacker-api
sha256:ca4dc9af82b89c9b146af2bddbcd34c292e380bd167ad97c39700e809bc29794
[7:33:24 AM] [semantic-release] › ✔  Completed step "prepare" of plugin "@codedependant/semantic-release-docker"
[7:33:24 AM] [semantic-release] › ℹ  Start step "prepare" of plugin "@codedependant/semantic-release-docker"
[7:33:24 AM] [semantic-release] [@codedependant/semantic-release-docker] › ℹ  building image ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e
[7:33:24 AM] [semantic-release] [@codedependant/semantic-release-docker] › ⬤  build command: docker build --quiet --tag ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e --build-arg SRC_DIRECTORY=cas-fee-adv-qwacker-api --build-arg TARGET_PATH=. --build-arg NPM_PACKAGE_NAME=qwacker-api --build-arg NPM_PACKAGE_SCOPE --build-arg CONFIG_NAME=cas-fee-adv-qwacker-api --build-arg CONFIG_PROJECT=smartive-education --build-arg GIT_SHA=7610ddae918477787e180ef01b4dabbb024d4b68 --build-arg GIT_TAG=v1.1.2 --build-arg BUILD_VERSION=1.1.2 --build-arg COMMIT_SHA=7610ddae918477787e180ef01b4dabbb024d4b68 -f /home/runner/work/cas-fee-adv-qwacker-api/cas-fee-adv-qwacker-api/Dockerfile /home/runner/work/cas-fee-adv-qwacker-api/cas-fee-adv-qwacker-api
sha256:ca4dc9af82b89c9b146af2bddbcd34c292e380bd167ad97c39700e809bc29794
[7:33:24 AM] [semantic-release] › ✔  Completed step "prepare" of plugin "@codedependant/semantic-release-docker"
```

and then pushing the first (google artifactory) does work, however when trying to push the ghcr images:
```
[7:34:01 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@codedependant/semantic-release-docker"
[7:34:01 AM] [semantic-release] [@codedependant/semantic-release-docker] › ℹ  tagging docker image cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e
[7:34:01 AM] [semantic-release] [@codedependant/semantic-release-docker] › ℹ  pushing image: ghcr.io/smartive-education/cas-fee-adv-qwacker-api tag: 1.1.2
[7:34:01 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@codedependant/semantic-release-docker"
[7:34:01 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: docker tag ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e ghcr.io/smartive-education/cas-fee-adv-qwacker-api:1.1.2
Error response from daemon: No such image: ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e
Error: Error: Command failed with exit code 1: docker tag ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e ghcr.io/smartive-education/cas-fee-adv-qwacker-api:1.1.2
Error response from daemon: No such image: ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e
    at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/@codedependant/semantic-release-docker/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/@codedependant/semantic-release-docker/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Image.tag (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/@codedependant/semantic-release-docker/lib/docker/image.js:121:5)
    at async publish (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/@codedependant/semantic-release-docker/lib/publish.js:29:5)
    at async validator (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: docker tag ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e ghcr.io/smartive-education/cas-fee-adv-qwacker-api:1.1.2',
  command: 'docker tag ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e ghcr.io/smartive-education/cas-fee-adv-qwacker-api:1.1.2',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Error response from daemon: No such image: ghcr.io/smartive-education/cas-fee-adv-qwacker-api:934b96dca07d0ae2ef7e',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@codedependant/semantic-release-docker'
}
```

**Comment by buehler** [comment]
addition: I already used this technique here: https://github.com/WirePact/k8s-contract-repository/blob/main/.releaserc.json

BUT the difference is, in the wirepact repo, it's two different dockerfiles
