### ISSUE TITLE
Auth not working with docker.io and ghcr.io

### ISSUE THREAD

**Issue by Disane87** [esatterwhite/semantic-release-docker#37]
Tahnk you for this great project! Actually I have an issue while authticating with `docker.io/dockerhub` and `ghcr.io`. Everytime I run da dry run with semantic-release, there is an error while authenticating:

> [12:47:58] [semantic-release] [@codedependant/semantic-release-docker] » ×  Error: Command failed with exit code 1: docker login ghcr.io -u [redacted] --password-stdin
Error response from daemon: Get "https://ghcr.io/v2/": denied: denied
    at makeError (C:\Workspace\Private\docudigger\node_modules\@codedependant\semantic-release-docker\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Workspace\Private\docudigger\node_modules\@codedependant\semantic-release-docker\node_modules\execa\index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doLogin (C:\Workspace\Private\docudigger\node_modules\@codedependant\semantic-release-docker\lib\verify.js:99:7)
    at async verify (C:\Workspace\Private\docudigger\node_modules\@codedependant\semantic-release-docker\lib\verify.js:57:5)
    at async validator (file:///C:/Workspace/Private/docudigger/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///C:/Workspace/Private/docudigger/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async file:///C:/Workspace/Private/docudigger/node_modules/semantic-release/lib/plugins/pipeline.js:32:5
    at async pluginsConfigAccumulator.<computed> [as verifyConditions] (file:///C:/Workspace/Private/docudigger/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///C:/Workspace/Private/docudigger/node_modules/semantic-release/index.js:106:3)
[12:47:58] [semantic-release] » ✘  Failed step "verifyConditions" of plugin "@codedependant/semantic-release-docker"

When I login with the same command on my prompt, it works pretty fine (but with `-p` instead of `--password-stdin`).

What I'm missing here?

**Comment by Disane87** [comment]
It was my fault :) consider this as closed
